---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCATION: uscentral1
  FAILOVER: ottawa
  SITE_ID: "4"
  TIMEZONE: America/New_York
  CLUSTER_NAME: gke-uscentral1

  # K8s
  CLUSTER_POD_CIDR: 10.7.0.0/16
  CLUSTER_SERVICE_CIDR: 10.6.0.0/16
  CLUSTER_LOAD_BALANCER_CIDR: 10.70.0.0/16

  # Networking
  LAN_CIDR: 192.168.70.0/24 
  LAN_GATEWAY_IP: "192.168.70.1"

  # Domain
  CLUSTER_DOMAIN: rajsingh.info

