---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./headlamp.yaml
  - ./1password.yaml
  - ./angelnu.yaml
  - ./argoproj.yaml
  - ./authentik.yaml
  - ./backube-charts.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./spegel.yaml
  - ./clabernetes.yaml
  - ./cloudnative-pg.yaml
  - ./clusterplex.yaml
  - ./coder.yaml
  - ./coredns.yaml
  - ./csi-driver-smb.yaml
  - ./descheduler.yaml
  - ./tailscale-helper-charts.yaml
  - ./emqx.yaml
  - ./envoy-gateway.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./nvidia.yaml
  - ./nvidia-device-plugin.yaml
  - ./fluent.yaml
  - ./grafana.yaml
  - ./harbor.yaml
  - ./kiali.yaml
  - ./immich.yaml
  - ./ingress-nginx.yaml
  - ./intel-charts.yaml
  - ./isovalent.yaml
  - ./itzg.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kserve.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./minio-operator.yaml
  - ./nextcloud.yaml
  - ./node-feature-discovery.yaml
  - ./ollama.yaml
  - ./open-webui.yaml

  - ./opencost.yaml
  - ./openebs.yaml
  - ./openspeedtest.yaml
  - ./opentelemetry.yaml
  - ./pihole.yaml
  - ./piraeus-charts.yaml
  - ./plane.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./prometheus-community-web.yaml
  - ./qdrant.yaml
  - ./redash.yaml
  - ./rook-ceph-charts.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml
  - ./strimzi.yaml
  - ./tailscale.yaml
  - ./twin.yaml
  - ./weave-gitops.yaml
  - ./wger.yaml
  - ./istio.yaml
  - ./homer-operator.yaml
  - ./aws-mountpoint-s3-csi.yaml
  - ./keda.yaml
  - ./kubeshark.yaml
  - ./vector.yaml
  - ./kuberay.yaml
  - ./liqo.yaml
  - ./capi-operator.yaml
  - ./actions-runner-controller.yaml
  - ./victoriametrics.yaml
  - ./unpoller.yaml
  - ./percona.yaml
  - ./fleetdm.yaml
  - ./mariadb-operator.yaml
  - ./bitnami.yaml
  - ./karmada.yaml
  - ./temporal.yaml
  - ./temporal-worker-controller.yaml
  - ./zot.yaml
  - ./woodpecker.yaml