---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: temporal-worker-controller
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://docker.io/temporalio
