---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium
  - ./csi-driver-smb
  - ./dockur
  - ./fleet
  - ./garage
  - ./gatus
  - ./immich
  - ./lan
  - ./media
  - ./pocket-id
  - ./rook-ceph
  - ./smartctl-exporter
  - ./tailscale-system
  - ./tuppr
