apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  route:
    groupBy:
      - alertname
      - cluster
      - job
    groupInterval: 5m
    groupWait: 1m
    receiver: discord
    repeatInterval: 12h
    routes:
      - matchers:
          - matchType: "="
            name: alertname
            value: InfoInhibitor
        receiver: blackhole
      - matchers:
          - matchType: "="
            name: alertname
            value: Watchdog
        receiver: blackhole
      - matchers:
          - matchType: "=~"
            name: severity
            value: critical|error|warning
        receiver: discord
      # Silenced alerts
      - matchers:
          - matchType: "="
            name: alertname
            value: DockerhubRateLimitRisk
        receiver: blackhole
      - matchers:
          - matchType: "="
            name: alertname
            value: ProbeFailed
        receiver: blackhole
  receivers:
    - name: blackhole
    - discordConfigs:
        - apiURL:
            key: DISCORD_ALERTMANAGER_WEBHOOK_URL
            name: alertmanager-secret
          message: |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message }}
              {{- else }}
                Alert description not available
              {{- end }}
              {{- if gt (len .Labels.SortedPairs) 0 }}
                Labels:
                {{- range .Labels.SortedPairs }}
                  {{ .Name }}: {{ .Value }}
                {{- end }}
              {{- end }}
            {{- end }}
          sendResolved: true
          title: '[talos-robbinsdale] [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}'
      name: discord
  inhibitRules:
    - equal:
        - namespace
        - alertname
      sourceMatch:
        - matchType: "="
          name: severity
          value: critical
      targetMatch:
        - matchType: "=~"
          name: severity
          value: error|warning|info
    - equal:
        - namespace
        - alertname
      sourceMatch:
        - matchType: "="
          name: severity
          value: error
      targetMatch:
        - matchType: "=~"
          name: severity
          value: warning|info
    - equal:
        - namespace
      sourceMatch:
        - matchType: "="
          name: alertname
          value: InfoInhibitor
      targetMatch:
        - matchType: "="
          name: severity
          value: info
