apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    DISCORD_ALERTMANAGER_WEBHOOK_URL: ENC[AES256_GCM,data:+lH0+DjIxCzfA+k6/6BOIqu1Qe2qUhssGGgApa9wxoMbq/OHCaoeRQHEuiqWiArjLf5O+7iEmdsqrGILMndrPWwVPXoK+jFnNtXvAtYDq2Fe3bWX3+dNQzjGMg9iPVotWmEr5PA6jyNGHOZA6toQV6HEtJHTCp+yvA==,iv:51T/zRWfm7gnu7Z4oVBDBE8DKqriVOaRERVmQd7uf1Q=,tag:55uz864JuK7JQI3GcBofcg==,type:str]
sops:
    lastmodified: "2026-01-22T02:39:23Z"
    mac: ENC[AES256_GCM,data:VtIXwhlDhyCfwTiHqeF3L1zv0KGa640ZSBaEp9GxvUq2R0dV/AjmMF1OKAQLXuAJboIiMJydWOneDnp4polOa6RD7QfT8GgHU84J0X/YI2fxg0h2j3VT6qnMvVjfgFd4qSqXuWAm7yFHXoGFAGkhgW38FD/poNWhPEV2xivr7vc=,iv:OFTxG63iToHdRH+7mdmloBqHAG2LCrqRsCT8342WEhA=,tag:nL27YDin/4lh8jE59VAuqw==,type:str]
    pgp:
        - created_at: "2026-01-22T02:39:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/+IW2MLd3NAJ4ahTKk4QvbJkfzo6YLtKUSf86SpTGeH07c
            6UvjEuBIYhgu6AlL/UgsWht7Az/Fh3DfeiGT8E2SE5JCsclXOEZ/DtAKJjXIUmsz
            8S6UE8rQqz9u0ART5qDOWRT2KVXfzWBDN4CnraUv+KqQHQndliVwxINXMF2MlU5j
            XQ0coElc+1maPuZQ50p8VOA0AK+DNpGe4s62oTOmrsXiDBJO1dv3sWV6mq4MUm8P
            Uu1VTrilmqadW+45DlGUoeSEcVVqKJjeQBcVY7zwxbVk6oxugXipPJoJgujH5v/Q
            8pWB2cn4AWe7YSXiJczNRxO1PjEvRiLA6Z5zbjkoQpUmG4JxlIqfTav42nCdJ3VN
            EOLEbuPN6Qcs+Qioc82byRY4f6oWWzBGavywFj93A3x7mZeoPf+kXdPssH0ukco3
            N4xzTagJCbhzOhD2PQo7n0rTgEhZk8mUMlJevoXCqxPBEKNT6nlDbBrlZVgGi/Ky
            ZvyMSy6vf83bRICYNmNTgJJDl8RhHV+FIgnYWR66svV9aX2248/NQXrvmoz1d8GU
            gL8aN7P07dxd7BvlXzQWux8NmYMtQrJ5efzGRhGrOaZ6ro1LAzkF8AMpnotrVFT6
            9vbOHhcOxoWLVXx7y67VgF5uRhDEgaaFiXpSfa2C1egtjD7JvX53SGmq3Z1x1kXU
            aAEJAhDXr7+MmfBzBK6ppNRulFQs964ZHzgbAt+w4yp69Dm7HB2QtC70GSLpbXoZ
            XFaKAIEYoIJvNX97leSCS3cwt2aU3lJswuxvfQOrIZW3MriDJCq6WG6SNdx32Ofu
            dVQ2tlF7rXKw
            =A8M7
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
