---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-secret.sops.yaml
  - alertmanagerconfig.yaml
  - scrapeconfig.yaml
  - prometheusrules.yaml
  - httproute.yaml