---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter-external
spec:
  staticConfigs:
    - targets:
        - nagato:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: node-exporter
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: opencost
spec:
  honorLabels: true
  scrapeInterval: 1m
  scrapeTimeout: 10s
  metricsPath: /metrics
  staticConfigs:
    - targets:
        - opencost.opencost:9003
  relabelings:
    - action: replace
      targetLabel: job
      replacement: opencost

