apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: silence-dockerhub-rate-limit
  namespace: monitoring
spec:
  route:
    groupBy: ['alertname']
    groupWait: 0s
    groupInterval: 0s
    repeatInterval: 0s
    receiver: 'null'
    matchers:
      - name: alertname
        matchType: equal
        value: DockerhubRateLimitRisk
  receivers:
    - name: 'null'
      nullReceiver: {}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: silence-probe-failed
  namespace: monitoring
spec:
  route:
    groupBy: ['alertname']
    groupWait: 0s
    groupInterval: 0s
    repeatInterval: 0s
    receiver: 'null'
    matchers:
      - name: alertname
        matchType: equal
        value: ProbeFailed
  receivers:
    - name: 'null'
      nullReceiver: {}
