---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${LOCATION}-woodpecker-webhook
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/proxy-class: "common"
spec:
  defaultBackend:
    service:
      name: woodpecker-server
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - ${LOCATION}-woodpecker-webhook
