---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woodpecker
resources:
  - bucket.yaml
  - helmrelease.yaml
  - pg.yaml
  - service-grpc.yaml
  - ingress.yaml
  - ingress-webhook.yaml
  - httproute.yaml
