---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woodpecker
resources:
  - helmrelease.yaml
  - pg.yaml
  - service-grpc.yaml
  - httproute.yaml
  - ingress.yaml
  - secret.sops.yaml
