---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - egress.yaml
  - httproute.yaml
  - httproute-code.yaml
  - ts-oauth.yaml
  - rbac.yaml
