---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
resources:
  - helmrelease.yaml
  - httproute.yaml
  - pg.yaml
  - redis.yaml
  - s3-backup.yaml
  - secret.sops.yaml
  - ./unifi-sync
