---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ai
  - ./cilium
  - ./cloudflare
  - ./gpu-operator
  - ./kserve
  - ./kuberay
  - ./local-path-storage
  - ./singh360
  - ./tuppr

