---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot
resources:
  - backendtrafficpolicy.yaml
  - bucket.yaml
  - helmrelease-internal.yaml
  - helmrelease-public.yaml
  - httproute-internal.yaml
  - httproute-public.yaml
  - ingress-internal.yaml
