---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
resources:
  - deployment-hello-world.yaml
  - service-hello-world.yaml
  # - configmap-nginx.yaml
  # - deployment-curl-hello-world.yaml
  - ingress.yaml
