---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./httproute.yaml
  - ./filesystem.yaml
  - ./toolbox.yaml
  - ./storageclass.yaml
  - ./volumesnapshot.yaml
  - ./blockpool.yaml
  # Dashboards
  - ./dashboard-cluster.yaml
  - ./dashboard-osd.yaml
  - ./dashboard-pools.yaml

