---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "k8s-pool"
spec:
  blocks:
    - cidr: "${CLUSTER_LOAD_BALANCER_CIDR}"
  serviceSelector:
    matchExpressions:
      - { key: somekey, operator: NotIn, values: ["never-used-value"] }