---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: ottawa-garage-operator.keiretsu.ts.net
  name: ottawa-garage-operator
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: s3
      port: 3900
      protocol: TCP
    - name: rpc
      port: 3901
      protocol: TCP
    - name: web
      port: 3902
      protocol: TCP
    - name: admin
      port: 3903
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: robbinsdale-garage-operator.keiretsu.ts.net
  name: robbinsdale-garage-operator
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: s3
      port: 3900
      protocol: TCP
    - name: rpc
      port: 3901
      protocol: TCP
    - name: web
      port: 3902
      protocol: TCP
    - name: admin
      port: 3903
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: stpetersburg-garage-operator.keiretsu.ts.net
  name: stpetersburg-garage-operator
spec:
  externalName: placeholder
  type: ExternalName
  ports:
    - name: s3
      port: 3900
      protocol: TCP
    - name: rpc
      port: 3901
      protocol: TCP
    - name: web
      port: 3902
      protocol: TCP
    - name: admin
      port: 3903
      protocol: TCP
