---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.yaml
  - ./rbac.yaml
  - ./peer-relay
  - ./testing
  - ./ds
  - ./tsdnsproxy
  - ./tsddns
  - ./derp-client