---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${LOCATION}-derp-client
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${LOCATION}-derp-client
  template:
    metadata:
      labels:
        app: ${LOCATION}-derp-client
    spec:
      serviceAccountName: "tailscale"
      containers:
      - name: tailscale
        imagePullPolicy: IfNotPresent
        image: "ghcr.io/tailscale/tailscale:v1.94.1"
        ports:
        - name: metrics
          containerPort: 9002
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TS_KUBE_SECRET
          value: ""
        - name: TS_STATE
          value: kube:$(POD_NAME)
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: ts-oauth
              key: TS_AUTHKEY_EPHEMERAL
              optional: true
        - name: TS_ACCEPT_DNS
          value: "true"
        - name: TS_EXTRA_ARGS
          value: "--advertise-tags=tag:k8s,tag:${LOCATION} --ssh"
        - name: TS_TAILSCALED_EXTRA_ARGS
          value: "--port=41641"
        - name: TS_ENABLE_METRICS
          value: "true"
        - name: TS_LOCAL_ADDR_PORT
          value: 0.0.0.0:9002
        - name: TS_HOSTNAME
          value: $(POD_NAME)