---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  labels:
    app.kubernetes.io/name: garage-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: garage-webui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GARAGE_ADMIN_API_URL
              value: "http://garage:3903"
            - name: GARAGE_S3_ENDPOINT
              value: "http://garage:3900"
            - name: GARAGE_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: garage-admin-token
                  key: token
                  optional: true
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
