---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  labels:
    app.kubernetes.io/name: garage-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: garage-webui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: khairul169/garage-webui:latest
          ports:
            - containerPort: 3909
              name: http
          env:
            - name: API_BASE_URL
              value: "http://garage:3903"
            - name: S3_ENDPOINT_URL
              value: "http://garage:3900"
            - name: API_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-admin-token
                  key: token
                  optional: true
            - name: CONFIG_PATH
              value: "/etc/garage.toml"
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: garage-config
