---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Note: namespace.yaml is NOT included here because karmada-system
  # namespace is already created by the karmada control plane kustomization
  - ks.yaml
