---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: monitoring
  path: ./clusters/common/apps/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: grafana
  dependsOn:
    - name: grafana
  path: ./clusters/common/apps/grafana/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-datasources
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: grafana
  dependsOn:
    - name: grafana-instance
  path: ./clusters/common/apps/grafana/datasources
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-dashboards
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: grafana
  dependsOn:
    - name: grafana-datasources
  path: ./clusters/common/apps/grafana/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
