---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: namespace is created by including namespace.yaml
# The HelmRelease will be created in karmada-system namespace
resources:
  - ../namespace.yaml
  - helmrelease.yaml
  - tailscale-service.yaml
