---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./servicemonitor.yaml
  # Dashboards
  - ./dcgm.yaml
  - ./nebius.yaml
  - ./gpu-metrics.yaml
configMapGenerator:
  - name: time-slicing-config
    files:
      - inference=time-slicing-config.yaml
    options:
      disableNameSuffixHash: true
