---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: argocd-application-overview
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  folder: ArgoCD
  grafanaCom:
    id: 19974
    revision: 5
  datasources:
    - inputName: DS_PROMETHEUS
      datasourceName: Prometheus
