apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tsflow-userspace-ha
  annotations:
    tailscale.com/proxy-group: "common-ingress-userspace"
    tailscale.com/tags: "tag:k8s"
spec:
  defaultBackend:
    service:
      name: tsflow
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - tsflow
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tsflow-userspace
  annotations:
    tailscale.com/proxy-class: "common-userspace"
    tailscale.com/tags: "tag:k8s"
spec:
  defaultBackend:
    service:
      name: tsflow
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - tsflow-userspace