apiVersion: v1
kind: Service
metadata:
  name: tsflow
  annotations:
    tailscale.com/hostname: "lb-tsflow"
    tailscale.com/proxy-class: "common-userspace"
    tailscale.com/tags: "tag:k8s"
spec:
  selector:
    app: tsflow
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  loadBalancerClass: tailscale