---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller
  - ./ai
  - ./argocd
  - ./blackbox-exporter
  - ./cdn
  - ./cert-manager
  - ./cloudflare
  - ./cnpg-system
  - ./coder
  - ./core-dns
  - ./csi-secrets-store
  - ./default
  - ./dragonfly-operator-system
  - ./envoy-ai-gateway-system
  - ./envoy-gateway-system
  - ./fluent-bit
  - ./flux-system
  - ./garage
  - ./garage-operator-system
  - ./grafana
  - ./harbor
  - ./headlamp
  - ./hello
  - ./home
  - ./homer-operator
  - ./hubble-ui
  - ./istio-multicluster-test
  - ./istio-system
  - ./keda
  - ./local-path-storage
  - ./mariadb-operator-system
  - ./monitoring
  - ./mountpoint-s3-csi
  - ./node-feature-discovery
  - ./opencost
  - ./pxc-operator-system
  - ./snapshot-controller
  - ./speedtest
  - ./spegel
  - ./tailcar
  - ./tailscale
  - ./tailscale-examples
  - ./tailscale-system
  - ./unpoller
  - ./victoria-logs
  - ./volsync

