---
apiVersion: v1
kind: Service
metadata:
  name: stpetersburg-llama-cpp
  annotations:
    tailscale.com/tailnet-fqdn: stpetersburg-llama-cpp.keiretsu.ts.net
    tailscale.com/proxy-group: common-egress
spec:
  externalName: placeholder
  type: ExternalName
  ports:
  - name: http
    port: 80
    protocol: TCP
