apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:NhRYulHsPlO+bBOtGOjg/qkyC3x4vG4leEEgcf3puLite0DWS3+OGNc3SaCto7g2pXF8jOnjMkt20ICzB8lolXUXzG639cii,iv:2ElkUjsYA7WeA1CoxVLWXzbaFiJE9IiHzXWlvK1t4wk=,tag:ZjSrle6MXvb3Btsmz6aXHQ==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:apwJrE86o+wX,iv:eiGO6/3b3uIG8mT/M1t2+/h0s3cvFCPf87TP3k4mSOA=,tag:VtkyZOUfKPwXVNg3/Yxc1Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:V8xlcDDy,iv:pXmwOWwQKDtQdd+rOrI2+syl8l7uNrIpa0Epfm2smzs=,tag:MFZyd6iqavviKRx8MYpSMw==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:DS49JJPreNSxcEa6AoW3bdBQ5aPxJBORme1D,iv:I38GQosGhMVBTTxWU0Gai9eKU1lA5LeHSTmt79eT0Z8=,tag:6CaLRhRcjiJ3VmBl2GsbEw==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:fVmA7edrnNmQOpDMyc4NFdvokoJcuuT02KVOXvw5bL/B2RsiooK4/kuw8Jjqed1w777461vxCJLGInadm3NBgpogGK+eCgOLRE9gWkM6Joq8KXvpMGkuqZ9Rwdz6/Vy0i/LYPPSrEBxdvGiI,iv:/IlDxio0ixYpc0PYUCxwhxUiN+Y+jlD8MHgvxL5WxQc=,tag:T4tuewQ9acvxB/C6PIpM/Q==,type:str]
    NVIDIA_API_KEY: ENC[AES256_GCM,data:K8XkK/p0lRXGS8UthQ+lizXsX5ClqE5ey6VKLG+OthoyTa2jnqwn2zVRJ5qSRX0Pr7F1iXLkIHLpvmHrbIK2RqXFektm+g==,iv:0Wl0DRKni1iW6pv0X9/yw6MO45hhtJmzvqIclr1kV4U=,tag:jTTB50WJcVkBwZjXiPoHQw==,type:str]
    BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:nzzeFoHSo/m33M0SQnXTOjwE9MATGP+kj6PftQ5tUA==,iv:3+PuKmXGNemG6VAYZXD9e6zSFmNkuTbT/In2aWxDLMs=,tag:erNNs4Neb31aA6jkEEeUUQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ZI8zmKArjMxtI6VYjZ5JppEugXqhljUBY83xp4YOUI6ldgQK055N5Q==,iv:KuG6ZxslJQcp7FGe/plMrk2S8+LYrrKs41kxW727DXU=,tag:RqChI66/XO9h/7IvqfRGyw==,type:str]
    GOG_ACCOUNT: ENC[AES256_GCM,data:u6wIRACIO3PPHfOEtWo2PWUsRh8=,iv:PLuKhJmLtQGPxINIeKSVSrEwg1u5XaOvU1wqYnkEnyw=,tag:ur2KJyOTavCpxumskx3qoA==,type:str]
    GOG_CLIENT_ID: ENC[AES256_GCM,data:ej2qwakYpSwJN3HbK3tSqEBOmKMI+s4aX1QczM3oiVXgdvRNSaR2xpqfvVdd6ttAkMsRroPUaLSyWr+8ozMkIBPR7uVXVJvIpw==,iv:6rxvG30mMFupPPYY6taeilc4e98Hn1Vva/q8v2A6amY=,tag:DrR2YxJwJCPfveWVyHx90A==,type:str]
    GOG_CLIENT_SECRET: ENC[AES256_GCM,data:8TyxJe+EZsgwL0oVvdO7ZfkMS5Kyni1d75g+Jt8/N6eZCNc=,iv:32tz5aUAMY+d6NNH1xdjlN1uddGu6IhdxDQjvdiWcUM=,tag:Zp2nKbfRIFZ5IEe+QyPKYQ==,type:str]
sops:
    lastmodified: "2026-02-13T02:14:32Z"
    mac: ENC[AES256_GCM,data:w3hr9dwgJOkDP7/FBupXuP5NvNUpelvrQ3dfycInyF+Q90vdDVW0SE/GvGGt34tUOhMisG2unBwNTmcd92QLT25T6MnoRKAsOkWwNr/UFYQ4quNCjyhfjXs1+rnJLWUL394Bg0VXVAObMPVXzTXMCTDBRMJpzD2QqlMWw9IzO0s=,iv:DOigewhf0mxGixDfpPooVX175YEfm3jsTSHrsx/lBaM=,tag:9FX36p44cmea+GDBE3H8CQ==,type:str]
    pgp:
        - created_at: "2026-02-06T05:08:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/8DiKYqW7u6Ass7JxNaKhImG7wfswwwqUGc1rKpgGzEpJI
            D3pqfTsT3JwsNG4BDzD2mNQ2vQuJ5mmEDI3n/x1lU2U/3cz863TyewLWD/o6oYXH
            v0x2A+DYSZJr789rmVG67X7vxTgZraGVGD7FVSzyG8+vGD0EfT16XBZ/oJoIQkAK
            i+28tc5Wwg9nUIGcWDIznjpvkJvVM0z/+uHzcdmRMPOxXPaL9knm6dlySh04sb1n
            9h/A+u1a2J7nQBsNu3xShYqXdIjkfbHPCnOVtSm4rvMinWfGOrzqQxGXS7R7/+Jc
            hud6yIpf2ao+nZlE56dD9YVrZeCIxveT4Gl9yq5niKFIlqdSuRB1c9SmdNz6a2os
            xRu7G4hiqVouvSUm/8Xk02apCUfwO+mloOk02kR0tO+XIFUKpvV8pqqKQdSW5FSF
            CO+oO48SaNFPRXlBWMNmpVJsYz1Q1QiLyF5H9TXPve+Rheb1vicv12Vj/kIPHUNM
            Wn7j8gPtUgJ71seVwWEc2sjVXFKgqrfXaiprZPBV24bFiXVSiX4AMQBl2D3d0LLK
            9knEWq3HzHxAhbqzFt983HgS+dQ4SGqAof4SdhVl0Sv5WfJy2zb0OSIZAmN5GIsh
            uVHYQmj6NHXriNM6biVlupmuw3Qgy1OPIYOLr5XGeMk9U8y/1DdIfeVNFoVkgYXU
            aAEJAhCgE0EnMTItqK+quI+wuDqgD76wSBDKVXwy0azeU/1P7j79HwtDukzJQAKA
            1PPtrmJJsc8YJwS4Qc3w76AQns257ss32G3zQzK9qGQxGn23PCT8BL17Nn/7usMb
            0c4CHU8zOOW5
            =OwGP
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
