---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: openclaw-data
spec:
  sourcePVC: openclaw-data
  trigger:
    schedule: "0 5 * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-openclaw-data
    retain:
      hourly: 1
      daily: 3
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Direct
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-openclaw-data
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:http://${COMMON_S3_ENDPOINT}/keiretsu/${LOCATION}/openclaw/data
  RESTIC_PASSWORD: ${COMMON_RESTIC_SECRET}
  AWS_ACCESS_KEY_ID: ${KEIRETSU_S3_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${KEIRETSU_S3_SECRET_KEY}
