---
# Karmada Member Cluster Registration
#
# IMPORTANT: These resources must be applied to the Karmada API server,
# NOT the host cluster. Flux cannot directly manage these resources.
#
# See bootstrap.sh for the registration process.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Service account to be applied to EACH member cluster
  - member-cluster-rbac.yaml
  
  # Cluster CRs (templates - tokens must be populated first)
  # These are applied to the Karmada API server after bootstrap
  # - cluster-ottawa.yaml
  # - cluster-robbinsdale.yaml
  # - cluster-stpetersburg.yaml
