---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml

# Create secret from kubeconfig.yaml for HelmRelease valuesFrom
secretGenerator:
  - name: karmada-agent-kubeconfig
    files:
      - kubeconfig.yaml=kubeconfig.yaml
    options:
      disableNameSuffixHash: true
