---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal
resources:
  - helmrelease.yaml
  - postgres.yaml
  - s3-backup.yaml
  - httproute.yaml
  - service-ts.yaml
  - cluster-mesh.yaml
