---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./1password
  - ./cert-manager
  - ./cilium
  - ./cloudflare
  - ./csi-driver-smb
  - ./garage
  - ./gatus
  - ./homarr
  - ./home
  - ./immich
  - ./media
  - ./rook-ceph
  - ./smartctl-exporter
  - ./speedtest
  - ./strimzi
  - ./tailscale
  - ./test
  - ./typeo
