---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laptop
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: laptop
  template:
    metadata:
      annotations:
        tailcar.rajsingh.info/inject: "true"
        tailcar.rajsingh.info/tailnet: keiretsu-labs-github
      labels:
        app.kubernetes.io/name: laptop
    spec:
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: zot-pull-secret
      containers:
        - name: laptop
          image: oci.${CLUSTER_DOMAIN}/laptop/laptop:latest
          imagePullPolicy: Always
          env:
            - name: PASSWORD
              value: "${DEFAULT_PASSWORD}"
            - name: ANTHROPIC_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: laptop-secrets
                  key: ANTHROPIC_API_KEY
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: laptop-secrets
                  key: GITHUB_TOKEN
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /home/coder
            - name: kubeconfig
              mountPath: /home/coder/.kube
              readOnly: true
            - name: startup
              mountPath: /entrypoint.d
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: laptop-data
        - name: kubeconfig
          secret:
            secretName: laptop-kubeconfig
        - name: startup
          configMap:
            name: laptop-startup
            defaultMode: 0755
