---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laptop
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml
  - pull-secret.yaml
  - secret.sops.yaml
  - kubeconfig.yaml
configMapGenerator:
  - name: laptop-startup
    files:
      - startup.sh
generatorOptions:
  disableNameSuffixHash: true
