apiVersion: v1
kind: Secret
metadata:
    name: laptop-secrets
type: Opaque
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:LfWh4TxklHPYLTvIULmiGs8EV1imDcvKpnBzvRgGvm1QSYGNisYX8eVilHPh76+000klcexpOVR5vCR0uzi8xm4DJc3DXeGwWFerOuYBqxB87xkx3DWYrLgeWoQJtoPlr31v8aNgOT9FEnca,iv:01QDsyRlvW2m7qVXqfhfuF4vEy9PX7pV8sEdNrvgGnE=,tag:9I9OOmlcd/SdXyObIS54lg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:1KHn7AEYLxgkXRPp3oyvHMGNG1gnfKjB+t9mhanogt44rQTCvm92aw==,iv:cqcLg8QFhz3GF/Kz4teeD5zMpcweF/MFeYUU+lKhwTs=,tag:wMg39tSzORKXp6BP7Uh+Aw==,type:str]
sops:
    lastmodified: "2026-02-16T06:11:16Z"
    mac: ENC[AES256_GCM,data:gzO4MC3u7WHcVxWsuVxr4n9RxxraE7SXjdgqR18f2sVLZssw8iCK7YJMQGsSAE9jeX9E/FsR1wCqqvXUAavT91t5sGErNbW4C0FaW5lPa7650Tj2QQNCiTG9CC15io8aaZ7pAEcjqzE2ldnCgenYArn2Vu9W6Pjlzo5taCu7wbw=,iv:Ia0AX3qqFZvvnvfzGntaWEIMrNN6KEYRbmSw4M1/z58=,tag:EL8lb9GtsCO1bvw4oQ2uWg==,type:str]
    pgp:
        - created_at: "2026-02-16T06:11:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/8CvcC9B6ISJKx1xBtx16+cZjahexywiybAExci9uX0fqZ
            paW6gXwPNQICsHQA+nXnCF7K/jSvuVGmwy6BDuDnKtxw2nobOxAWLFTVwUG+RYuQ
            9kDHhrIO1P5kuIGWHbvPtlmtzzgyA0+IL4nCfoBvXTyHUt8bkFBo0MBw4W5RqOtk
            kLRFQXGj069WRYAB1BcLZJvWJ38sFQep5aO14E4RKboNWUBQTZHt81Rb6N5UvW6K
            2QHrzZTwPh+G7uBMoopKutk/E8CAFfRmyjb3T+jVKvOd+DVI+8vuYxmg9KfCzhL9
            DVPd2xBqn0YQRw4elAD3G+RmUgV1dXNPTf9KsH4oO75XjliPtA3vnjDvfundriLu
            stzkbWAYQ0yVQEx1qI3Ygf5+7On+W0VAq3suPSuEE2zUUaM8FGIZfrCEZHjjB/8p
            NMv3jT72Nr/M8sS+KExrRwZRy/uu0ZZYrIUXK1RPg7JiIX779LSLMVgDoCxL7d2Y
            5pJbQreUY4PcDB0qCQcH/wxgu3wVg4LylMBDE86S5XeSNEjT9+7+dBqvKeXLiZ/6
            LbNFFvNBv61s2nCPQPu1DRADftC+PTIkIgphD1KAvWKEGK1s6C4b6JsWTKVAd3Gf
            gkMEX1D5vbg80MxdguGPhkm046HkU3nmDjnjlrzfcip/mWijx60EmVTmaOF4OaTU
            aAEJAhCTT9yWHQ4339MMPzKHNSOXBoFzf7LzYwNHnO6p9Ri32BhV/8jucq9pAWZj
            74KemFr89A4naS9RUkCijBOAaGOipYJDl5RYQE8o9ltTTjZsa13CnI0QFCjOhouz
            02X8OvN7hOHA
            =4aAZ
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
