apiVersion: v1
kind: Secret
metadata:
    name: laptop-secrets
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:8m8K3rjTE8fMGBDvqg38UDML5zXOuJqViM4DoneZdGChUWutcbnIwvhQ2unMDVoLgy0RyvW1jNKHYN0dFagKT7/G2UKWPH9ST6I3c7Ym+uEFmjkBl2hXHDLTcD8PZriheo7lLAadFARjOEZq,iv:Wm+5C06MfpgS3Jxrxb8N7/jpQaqp6XXOUXLnlS01I9I=,tag:FJRnRnJ40JPNJZwChqJ6bg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:OyQNtDbqWM6s6Phq73RIDreLV9OwPyN92/wjwFnPfshZSTus05NuiA==,iv:PCLJ8/B5eJ5MA4X2uajN4X3aiuIVRF46gNV4ON+KaYA=,tag:DdKvb3qKrSA5I+JeRccp1A==,type:str]
    PASSWORD: ENC[AES256_GCM,data:vkQ6dySRTXSpUfYlT7atjcdeHA==,iv:wyCbXglard7yJkZ/4iXh+QeZ8cO2Wh7OOnpxGartGUo=,tag:d5TKyOlJLQnnTZ010QdSQA==,type:str]
sops:
    lastmodified: "2026-02-16T04:48:29Z"
    mac: ENC[AES256_GCM,data:8deUhRhwWtwQWTsKoo4jkUfreVSmZQKe1lx5xzboX5rg7iSiaZA1DTX9l4BEaN7GtP70OmsI/niRRSsLORrOGoxs2jQJfhU0Zd5FySUkGAsSJQxirTm5b9H7QHqFlLHkVulSqhti4vm5UmyuD/GpGQt8+m0ZxR0EG84ZTzhWGKs=,iv:FkdqFmYUFYTGrV9CmQ2wGf5tbO+Mg4bdfSLn1iFHt3w=,tag:267umnB8nSYXTB/349+Ckg==,type:str]
    pgp:
        - created_at: "2026-02-16T04:48:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveAQ/+KG0KHd+qQEE9RzC0gMNgKdFHOk2fYVgCcu3hHkMic+Xq
            ObP6P+qYh38+eUaaHNawsyTvIf2M0MyB1gb0iYa+GaTjuez9K+jZ1gGPXUgtwpTa
            N5oOBxI8k5Rpjr3Oo9LRowTmPfGr5I4vmHBSC7ZyI10uYjNNp1cHqxqFUf5zFc+Y
            76Aji6MTvUdR+AQUlsQjwGQIMc+MV3vdv+mrW5srjLvBNEPsO+/5pE5Wss8xVclu
            ky/cTmgxAxXhVSBTTt5chzCbBkRQNkEBQEwmTeMXf803skpbec2bxG76DLJfXJoS
            qWr74DEyqnMMdAjKVwOm4XzkG9z15qC2gowNdo85c2FTFlglfx1pLQPac05LqooB
            Rrs5YexF/Imh9IPkfZqroJb7m6ks0qAirYpP36nabOHFTW0fvJ/QB/UP0Rzkve7t
            EIGRu3yMJS1N0soTo9uo7ozDzkvo6s2gvhHA08T9eIUjBQQhfEn8uCOPI+G506Ts
            XUPaRmRccXs7BUxvxf886MMhzqpm4vw0h9AUEtxXM6La6oz6jAusYD0oas8ReAwO
            SlKyTfcF7bWDbu5ep98K/AFKVeduwz97occ724P40kllU4RBWkqQKGFk+ouofhZ3
            V8u8HKkuDCy5NZld+raUl97nLcFI86l/bkZ4v5un9+yXrUPTRfAJea4NqF9hARDU
            aAEJAhDjrPQAZLeL88u0iL60zXa4tS7q/f2qcF4YlaDr5aYIsliE0jSOpOgEztsq
            Z5nbSzfkbFL37eQTsl3BbuL9r2Miqacy8w1ZnWErFmdDfOGUxppKKuxU9JzOkPmT
            aloTgaN6wSDf
            =fQ6G
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
