apiVersion: v1
kind: Secret
metadata:
    name: laptop-secrets
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:K7td7oaVrxjj5koNw9J3M/0mJVWAT5+Oxyf3fAfXaGn0WBpGFSIgeWywysnlmvIeDIZkYsAWtnBlBLMVAoLeIbh8GMt4RpL5K7dX1PYcBEwcb3WOSF2Ym+CSS0ohSlFpzhG49gzx3MFIC5el,iv:WJRq0/dI/o7QTbqobsRN8vr99WhCHgsd2da7BPmvuBY=,tag:OF6WVCz7rDo1+SoOsIX1Mw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:8MdAQk116pWyxnNdWzg+VXUqQXozIGjgVhJttMoEOyBXw39BQbQ+xw==,iv:+PDG2OvMyb8etapvJ8VB5wMMj1wh5OxV+5ehkivd1Z4=,tag:bVcJ3V5O9IYw1jN2MUY0ug==,type:str]
sops:
    lastmodified: "2026-02-16T05:17:23Z"
    mac: ENC[AES256_GCM,data:S+pjZRwDFurC2BI1gR41wfKFsrEUC5ZWZbM19dc4Ki8I2LcoI6fHSW8blo4I8XwNls7ov/e6RRb01Qujzk6YMhiqMtV/ZBJc/aXSHac1CJoGDGFukm87/yM7ejfmO1YSAaEK40z3pi0l7j08xNTmzi3NYQym2UMNztnKXB46Lts=,iv:tvd2Bk02OthWYYsxIlGUHR+pB65b49NFqMFZBr9lab0=,tag:qAMHpwac7GFtcaBbbqg7ig==,type:str]
    pgp:
        - created_at: "2026-02-16T05:17:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAApGEQXre9L8lc2PDO3SsaViOgLbxhmiOKwd/FW9g5rCt+
            K8fVtnU0hRHGr/FJXvbREHwhGxDoD3xNud/9/OHbPUifOOZb92ccjILU8NCAMYuA
            asyPnOktR9yaKGXi77kOFJ0dKeBlX/pBsmEiC5iOWpr5xG23dGLw/KoW9ErrDRyT
            xmUVAjvp0G86sJ+mKPh7R4RSiCP1SM2xcLeATKdP5FLjfHwD87nD0Pye2/GPkeFo
            /w7ZKJLHHdghO1udpfjyPYzzMtfMguWONozveR6zzrRIUwmSRrH0Wf1Q5aKOzf0h
            fPYPe0qNQ/tP9i8WaQ44R9SramU+M6cdvM0ERZglIxk0NEe+wv71ChG2LbH17GnV
            UNc84g/yCNRTZogpoxx3iG/w/GcWzaJ2He7qTAnST2VDd/Ut4Wye/n2lZ1xJ6gSF
            3Sik7Aj/2Q2Yt8MHQQvrQH+I3HcLN0ft4NbuPCr1yD/DpnselPPmRWObiztnrTdA
            EuLS7ZoEmlo/+ysi2pqei9nmrQ7aMzNPW3k5Jciny/KspYue61P8eqP5SG9zgKGM
            liIqD91QbtRep9pmYYO/L4HOuGkJ8B2bTj9oTo1VfennlBs4TBj2fSTz3nfjwXhc
            FcNruQFvhuzbWTw+n6b94/LIR7T5P3Q/siVLJJ2Np+LZSlMTf/abqhhrVSYCryLU
            aAEJAhANOvRtTw2e8mE3KhWk+Ilj4d5L0ZFSsNjS2IyUD2T8Pi/YHknzzuZBsIEm
            JpS4gkhkaDVVXpmTtWxvnPGrT6oTQtWmYps+SirCFvag1F7PFNkeylBKieFZ1Thn
            qhbR37xzXv+J
            =3a69
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
