---
apiVersion: v1
kind: Service
metadata:
  name: laptop
spec:
  selector:
    app.kubernetes.io/name: laptop
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: laptop-ts
  annotations:
    tailscale.com/hostname: "${LOCATION}-laptop"
    tailscale.com/proxy-group: common-ingress
    tailscale.com/tags: "tag:k8s,tag:${LOCATION}"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: laptop
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
