metadata_dir = "/mnt/meta"
data_dir = "/mnt/data"
db_engine = "lmdb"
block_size = 1048576
replication_factor = 3
compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"
bootstrap_peers = [
    "60ba077f4bce25371ef61acea17b3078881d8de6a6301c0f2f7564096c23ca84@ottawa-garage.garage.svc.cluster.local:3901",
    "42dbead9647961510803e53b02f521784ff0b6714e2614a576564bae871d8490@robbinsdale-garage.garage.svc.cluster.local:3901",
    "cee1c1ced31d9593f2e2017e6bb15d7095afd27ddcf9948f7dc69412904074b2@stpetersburg-garage.garage.svc.cluster.local:3901"
]

[s3_api]
s3_region = "${LOCATION}"
api_bind_addr = "[::]:3900"
root_domain = ""

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".garage"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${GARAGE_ADMIN_TOKEN}"
