metadata_dir = "/mnt/meta"
data_dir = "/mnt/data"
db_engine = "lmdb"
block_size = 1048576
replication_factor = 3
compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"
bootstrap_peers = [
    "12a179af155723929505e3c73d5919eddedf8ce35dedf8deca5a10477f955d86@ottawa-garage.garage.svc.cluster.local:3901",
    "580a8542a8c72deef7bc5e99016b2ae9903068d3cf4c6d69f8573d1961ab6f13@robbinsdale-garage.garage.svc.cluster.local:3901",
    "b5c11fd0733fd4c405d22f43e07c458b6a7c8f3e986694c63fddd7a43c70436a@stpetersburg-garage.garage.svc.cluster.local:3901"
]

[s3_api]
s3_region = "${LOCATION}"
api_bind_addr = "[::]:3900"
root_domain = ""

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".garage"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${GARAGE_ADMIN_TOKEN}"
