metadata_dir = "/mnt/meta"
data_dir = "/mnt/data"
db_engine = "lmdb"
block_size = 1048576
replication_mode = "1"
compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"
bootstrap_peers = [
    "bb6ab68f244b5f5a@ottawa-garage.garage.svc.cluster.local:3901",
    "395215de7e198c16@robbinsdale-garage.garage.svc.cluster.local:3901",
    "6a0590a7f0c102d8@stpetersburg-garage.garage.svc.cluster.local:3901"
]

[s3_api]
s3_region = "${LOCATION}"
api_bind_addr = "[::]:3900"
root_domain = ""

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".garage"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
