metadata_dir = "/mnt/meta"
data_dir = "/mnt/data"
db_engine = "lmdb"
block_size = 1048576
replication_factor = 3
compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_secret = "${GARAGE_RPC_SECRET}"
bootstrap_peers = [
    "b7fc0f0cd77e79c4351e6d620c5b607c292fe99b5ff2687a2a4a94c0a78417a9@ottawa-garage.garage.svc.cluster.local:3901",
    "a6eb4f743db997419993f5382c6b67df576a6003f659fbb48c79acdeac18783e@robbinsdale-garage.garage.svc.cluster.local:3901",
    "2b791dee25717fc62ad19c94830b00f94786408dc408a3f081524c630e3178b2@stpetersburg-garage.garage.svc.cluster.local:3901"
]

[s3_api]
s3_region = "${LOCATION}"
api_bind_addr = "[::]:3900"
root_domain = ""

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".garage"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${GARAGE_ADMIN_TOKEN}"
