---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
resources:
  - helmrelease.yaml
  - egress.yaml
  - service-local-ts.yaml
  - service-global-ts.yaml
configMapGenerator:
  - name: garage-config
    files:
      - garage.toml
  - name: garage-grafana-dashboard
    files:
      - garage.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: garage
generatorOptions:
  disableNameSuffixHash: true