---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
resources:
  - admin-token.yaml
  - egress.yaml
  - service-ts.yaml
  - garagecluster.yaml
  - rpc-secret.yaml
  - httproute-s3.yaml
  - probes.yaml
configMapGenerator:
  - name: garage-grafana-dashboard
    files:
      - dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: garage
generatorOptions:
  disableNameSuffixHash: true