---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Envoy
  - gatewayclass.yaml
  - gateway-cdn.yaml
  - envoyproxy.yaml
  - certificate-wildcard.yaml
  - redirect.yaml
  - clienttrafficpolicy.yaml
# DNS
  - secret.yaml
  - external-dns.yaml
