---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - istio-base.yaml
  - istio-istiod.yaml
  - istio-eastwestgateway.yaml
  - istio-eastwestgateway-internal.yaml
  - istio-cross-network-gateway.yaml
  - tailscale-eastwest-egress.yaml
  - tailscale-kubeconfig.yaml