temporal:
  address: "ottawa-temporal.keiretsu.ts.net:7233"
  useTsnet: true
  namespace: "default"
  taskQueue: "swarm-kube-events"
tailscale:
  hostname: "swarm-kube"
  tags:
    - "tag:swarm"
clusters:
  - name: robbinsdale
    endpoint: "robbinsdale-k8s-operator.keiretsu.ts.net:443"
  - name: ottawa
    endpoint: "ottawa-k8s-operator.keiretsu.ts.net:443"
  - name: stpetersburg
    endpoint: "stpetersburg-k8s-operator.keiretsu.ts.net:443"
