---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swarm
resources:
  - connection.yaml
  - worker-deployment.yaml
  - service.yaml
  - httproute.yaml
  - pull-secret.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: swarm-config
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
