---
apiVersion: v1
kind: Secret
metadata:
  name: zot-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"oci.${COMMON_DOMAIN}":{"username":"${OCI_USERNAME}","password":"${OCI_PASSWORD}"}}}'
