apiVersion: v1
kind: Secret
metadata:
    name: swarm-secrets
stringData:
    TS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:WH3qiZnfQdC1ZDtav1+yjVI=,iv:qUtElmsJmAY1rfDUcTNToyv4kCXsz2pm7rpZl1x/AfM=,tag:ZemmcCPfbA+dVzt1t/mWAg==,type:str]
    TS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:rI3+Q9eVriyMpQK1jK2L1n3xS25fqL3qLPaBMvbx7w90Z09ba1YIZJnwMVXv8sziDppthgZDcKe2i3ppkYAQ,iv:KEa9RuVGz72QUWW05e7+aJIRoJ7HFJ3gc92uEJrwMhU=,tag:NWu9gE/Ex+DN2nA8FEsI8g==,type:str]
sops:
    lastmodified: "2026-02-14T04:37:21Z"
    mac: ENC[AES256_GCM,data:tcirODcsNffXlgBjsFIQ3WHzPLOsAHIr7i7IYnJB5Q8cP7+ee8rTbT6UmVJle2ZbT1UvXv4YpqgYSBUu+mq1v1Q9/+dESMECg4SWRwCyP1k61kQ2i4GvYHLJ1W5ezIV6QZ3FgAoidBEAaXxw17fPeBMWTC3FVFUPmmN2rGAvFCU=,iv:5UhWM/UQLLfpOMtjywU+ZozXr3HG3YxIMlsZk63DqTI=,tag:MbtIH/wTxWLBM/EDE6+QBQ==,type:str]
    pgp:
        - created_at: "2026-02-14T04:37:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0HSi2TJaWveARAAjQt3sMt0wpDI5+FpGBi1JAYtNc5E5oNBvfHq8PL5I3yA
            iWnmVmWjjqcYuQU8nlViykNNjIF9LG/vGhG/jengyDGNQZGJoIt++THFR9H2bu7V
            DxGTYF6LU1kZ+PxbizaxaQOEuY3qTxsIYNINhoCoUqOL842esxT41BNvm0TAU7tN
            Dh/oYQa+tPtjDNvls8o27KUPIHJnb7YIBVW5r9corAnCkVpfmtpbBducxq85vYe/
            v8FVaPwD3kw9btpr5wZGK9RHSdQDRVj/ztMqOHT8G+LCopCTy3gU9UEIYErUjPhf
            PQPo6pGs0/NuBivEV4k0D1gqXKK2OfIrptsalzgiw7aRugDZEFH6TBpMNvX8JxTI
            fx5kLpMtcD5TnHk9LUR7wtzN0QAuOpa31AaCbi+Zz6/pSo22YX6V3Lghz5ww3TFg
            RvpGMNv45EXHa/0Wlh9yr+i0Cos06KcX38oPF8kaKnr4nClYwaIiVgMETAZ6DwQK
            2EqMpyhoe9LkJgCKOFSfSXou/oJpJLK7JYfL6SsOCM+JAyMefAEFG95snUmidGbe
            a+p8uGFoJLLbNTE+QNPe6KSpETidsfxMRzZJqJW+MtE/XLcfU9VkTA43hvvI9aYm
            FivXyd06O3Bq0pAqpNZMSUUA3gcY8RkouQ9Z7Kv1HSMyTjyVq8/isqUiUtqcSlvU
            aAEJAhCYG27Tj4n+cEZQpN6QN7t4YF6gDAI9LoP0aFOp2cjDnkrXFsTyJPcnD+zR
            2delkFjYvZw2aV47Z1OfjrzWEVW/32s2kRtUByoSeeeyTCvvZyWs9eHGUOvGKc9K
            eltvA5PHcoZJ
            =pV5K
            -----END PGP MESSAGE-----
          fp: FAC8E7C3A2BC7DEE58A01C5928E1AB8AF0CF07A5
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
